#!/bin/sh
#
# PROVIDE: dnssec_validator
# REQUIRE: LOGIN
# KEYWORD: shutdown
#
# Add the following lines to /etc/rc.conf to enable dnssec_validator:
#
# dnssec_validator_enable="YES"
#

. /etc/rc.subr

name="dnssec_validator"
rcvar="dnssec_validator_enable"

load_rc_config $name

: ${dnssec_validator_enable:="NO"}
: ${dnssec_validator_user:="www"}
: ${dnssec_validator_env:="/usr/local/etc/tudordns/dnssec-validator.env"}

pidfile="/var/run/${name}.pid"
# Use wrapper script - daemon command strips environment variables
# Log file is configured via LOG_FILE env var, not shell redirection
command="/usr/local/sbin/dnssec-validator.sh"
command_args="&"

start_precmd="${name}_prestart"
stop_postcmd="${name}_poststop"

dnssec_validator_prestart()
{
    # Create log directory if needed (app writes to LOG_FILE from env)
    install -d -o ${dnssec_validator_user} /var/log/tudordns

    # Set env file path for wrapper script
    export DNSSEC_VALIDATOR_ENVFILE="${dnssec_validator_env}"
}

dnssec_validator_poststop()
{
    rm -f ${pidfile}
}

run_rc_command "$1"
