#!/usr/bin/env python3
"""Collect upstream license/notice files for modules in GoReleaser binaries."""

import argparse
import json
from pathlib import Path
import subprocess
import sys


def run(*args):
    return subprocess.check_output(args, text=True).strip()


def notice_text(path):
    # Normalize trailing whitespace while retaining every notice's wording.
    return "\n".join(line.rstrip() for line in path.read_text().splitlines()).rstrip() + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dist", type=Path, default=Path("dist"))
    parser.add_argument("--go-license", type=Path, help="Go LICENSE when installed outside GOROOT")
    parser.add_argument("--check", action="store_true", help="fail if checked-in notices need updating")
    args = parser.parse_args()
    root = Path(__file__).resolve().parent.parent
    artifacts = json.loads((args.dist / "artifacts.json").read_text())
    binaries = [Path(item["path"]) for item in artifacts if item["type"] == "Binary"]
    if not binaries:
        raise ValueError("No release binaries found; run make snapshot first")

    modules = set()
    toolchains = set()
    for binary in binaries:
        # Read build metadata; never execute a daemon or a foreign-OS binary.
        lines = run("go", "version", "-m", str(binary)).splitlines()
        toolchains.add(lines[0].split()[-1])
        for line in lines[1:]:
            fields = line.split()
            if fields and fields[0] == "=>":
                raise ValueError("Replaced modules need an explicit upstream-license review")
            if fields and fields[0] == "dep":
                modules.add((fields[1], fields[2]))

    current_go = run("go", "env", "GOVERSION")
    if toolchains != {current_go}:
        raise ValueError("Use the same Go toolchain that built the release binaries")
    go_license = args.go_license or Path(run("go", "env", "GOROOT")) / "LICENSE"
    cache = Path(run("go", "env", "GOMODCACHE"))
    output = [
        "# Third-party notices\n\n",
        "The project itself is MIT-licensed; see LICENSE. Its static Go binaries\n",
        "also contain the Go runtime and third-party modules under their own terms.\n",
        "This file preserves upstream license, copyright, and NOTICE files for the\n",
        "union of modules recorded in all release targets. A particular executable\n",
        "may use only a subset. It does not relicense those components.\n\n",
        "Generated by scripts/update-notices.py from GoReleaser build metadata.\n",
        "Review dependency license changes when updating this file.\n\n",
        f"## Go runtime and standard library ({current_go})\n\n",
        "Source: https://go.dev/LICENSE\n\n```text\n",
        notice_text(go_license) + "```\n",
    ]
    for module, version in sorted(modules):
        # Go's module cache escapes uppercase letters as !lowercase.
        escaped = "".join("!" + c.lower() if c.isupper() else c for c in module)
        directory = cache / (escaped + "@" + version)
        if not directory.is_dir():
            raise ValueError(f"Missing module cache entry: {module}@{version}; build first")
        notices = sorted(
            p for p in directory.rglob("*")
            if p.is_file() and p.name.upper().startswith(("LICENSE", "COPYING", "COPYRIGHT", "NOTICE"))
        )
        if not any(p.name.upper().startswith(("LICENSE", "COPYING")) for p in notices):
            raise ValueError(f"No license found for {module}@{version}; review it before releasing")
        output.append(f"\n## {module} {version}\n")
        for notice in notices:
            output.append(f"\n### {notice.relative_to(directory)}\n\n```text\n")
            output.append(notice_text(notice) + "```\n")

    target = root / "THIRD_PARTY_NOTICES.md"
    generated = "".join(output)
    if args.check:
        if not target.exists() or target.read_text() != generated:
            raise ValueError("THIRD_PARTY_NOTICES.md is stale; run scripts/update-notices.py after make snapshot")
    else:
        target.write_text(generated)
    print(f"{target.name}: {len(modules)} module versions, {len(binaries)} release binaries")


if __name__ == "__main__":
    try:
        main()
    except (OSError, ValueError, subprocess.CalledProcessError) as error:
        sys.exit(str(error))
